name: Draw ZMK keymaps

on:
  workflow_dispatch:
  push:
    paths:
      - "config/*.keymap"
      - "config/*.yml"
      - "config/*.dtsi"
      - "config/config.yml"
      - ".github/workflows/draw-keymaps.yml"
jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write # allow workflow to commit to the repo
    with:
      # Use the triggering commit's message, prepending the "[Draw]" tag
      amend_commit: true
      keymap_patterns: "config/*.keymap"
      config_path: "config/config.yml"
      output_folder: "keymap-drawer"
      parse_args: ""
